import { IconComponent } from './component'
import {
  CheckCircleFilled,
  CheckSquareFilled,
  CloseCircleFilled,
  CloseSquareFilled,
  ExclamationCircleFilled,
  InfoCircleFilled,
  QuestionCircleFilled,
  StopFilled,
  WarningFilled,
  CheckOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  CloseSquareOutlined,
  ExclamationOutlined,
  ExclamationCircleOutlined,
  InfoOutlined,
  InfoCircleOutlined,
  MinusOutlined,
  MinusSquareOutlined,
  PlusOutlined,
  PlusSquareOutlined,
  QuestionOutlined,
  QuestionCircleOutlined,
  StopOutlined,
  WarningOutlined,
  AlarmFilled,
  AlarmClockFilled,
  AppStoreFilled,
  ApproveFilled,
  ArchiveFilled,
  AssetMonitorFilled,
  AudioFilled,
  BankCardFilled,
  BellFilled,
  BlockFilled,
  BookmarkFilled,
  BuildingFilled,
  BulbFilled,
  CalculatorFilled,
  CalendarFilled,
  CameraFilled,
  ChatFilled,
  CloudFilled,
  CloudDownloadFilled,
  CloudUploadFilled,
  CollectionFilled,
  DataMonitorFilled,
  DislikeFilled,
  DocumentFilled,
  DocumentExclamationFilled,
  EndDateFilled,
  ExpressionFilled,
  FileFilled,
  FireFilled,
  FlagFilled,
  FolderFilled,
  FolderOpenFilled,
  HeartFilled,
  HomeFilled,
  KeyFilled,
  LightningFilled,
  LikeFilled,
  LocationFilled,
  LockFilled,
  MailFilled,
  MailOpenFilled,
  MailSendFilled,
  ManFilled,
  MessageFilled,
  MobileFilled,
  MonitorFilled,
  MoonFilled,
  PadFilled,
  PauseFilled,
  PhoneFilled,
  PictureFilled,
  PinFilled,
  PlayFilled,
  PrinterFilled,
  QrCodeFilled,
  RelationFilled,
  RmbFilled,
  SadFilled,
  SettingFilled,
  ShoppingFilled,
  SkinFilled,
  SoundFilled,
  StarFilled,
  StartDateFilled,
  SunFilled,
  TagFilled,
  TaskFilled,
  TemplateFilled,
  TimeFilled,
  ToolFilled,
  TravelFilled,
  TruckFilled,
  UmbrellaFilled,
  UnlockFilled,
  UpdateFilled,
  UserFilled,
  VideoCameraFilled,
  WebpageFilled,
  AlarmOutlined,
  AlarmClockOutlined,
  AppStoreOutlined,
  ApproveOutlined,
  ArchiveOutlined,
  AssetMonitorOutlined,
  AudioOutlined,
  BankCardOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookmarkOutlined,
  BuildingOutlined,
  BulbOutlined,
  BusinessCardTransverseOutlined,
  BusinessCardOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  ChatOutlined,
  CloseCodeOutlined,
  CloudOutlined,
  CloudDownloadOutlined,
  CloudUploadOutlined,
  CollectionOutlined,
  DataMonitorOutlined,
  DiagramOutlined,
  DislikeOutlined,
  DocumentOutlined,
  DocumentExclamationOutlined,
  DownloadOutlined,
  EndDateOutlined,
  ExportOutlined,
  ExpressionOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FileOutlined,
  FileExcelOutlined,
  FileExeOutlined,
  FileJpgOutlined,
  FileKeynoteOutlined,
  FileMusicOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileQuestionOutlined,
  FileTxtOutlined,
  FileVideoOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FireOutlined,
  FlagOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  GlobalOutlined,
  HeartOutlined,
  HomeOutlined,
  ImportOutlined,
  KeyOutlined,
  LightningOutlined,
  LikeOutlined,
  LinkOutlined,
  LocationOutlined,
  LockOutlined,
  MailOutlined,
  MailOpenOutlined,
  MailSendOutlined,
  ManOutlined,
  MenuOutlined,
  MessageOutlined,
  MobileOutlined,
  MonitorOutlined,
  MoonOutlined,
  PadOutlined,
  PauseOutlined,
  PhoneOutlined,
  PictureOutlined,
  PinOutlined,
  PlayOutlined,
  PowerOffOutlined,
  PrinterOutlined,
  QrCodeOutlined,
  RelationOutlined,
  ResetOutlined,
  RmbOutlined,
  SadOutlined,
  ScanOutlined,
  SearchOutlined,
  SendOutOutlined,
  SettingOutlined,
  ShareOutlined,
  ShopOutlined,
  ShoppingOutlined,
  ShowCodeOutlined,
  SkinOutlined,
  SoundOutlined,
  StarOutlined,
  StartDateOutlined,
  SunOutlined,
  SynchronizeOutlined,
  TagOutlined,
  TaskOutlined,
  TemplateOutlined,
  TimeOutlined,
  TimeRewindOutlined,
  ToolOutlined,
  TravelOutlined,
  TruckOutlined,
  UmberOutlined,
  UmbrellaOutlined,
  UnlockOutlined,
  UpdateOutlined,
  UploadOutlined,
  UserOutlined,
  UserAddOutlined,
  UsersOutlined,
  VideoCameraOutlined,
  WebpageOutlined,
  WomanOutlined,
  CaretDownFilled,
  CaretLeftFilled,
  CaretRightFilled,
  CaretUpFilled,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  ArrowUpOutlined,
  DirectionDownOutlined,
  DirectionLeftOutlined,
  DirectionRightOutlined,
  DirectionUpOutlined,
  DownOutlined,
  ExpandOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  LeftOutlined,
  LeftRightOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  RightOutlined,
  ShrinkOutlined,
  ToBottomOutlined,
  ToTopOutlined,
  UpOutlined,
  CopyFilled,
  DeleteFilled,
  DetailsFilled,
  DuplicateFilled,
  EditFilled,
  EllipsisCircleFilled,
  EmptyFilled,
  FilterFilled,
  FolderAddFilled,
  FolderMoveFilled,
  PasteFilled,
  AverageOutlined,
  ColumnHeightOutlined,
  ColumnsOutlined,
  CopyOutlined,
  DeleteOutlined,
  DetailsOutlined,
  DocumentSearchOutlined,
  DragOutlined,
  DuplicateOutlined,
  EditOutlined,
  EllipsisCircleOutlined,
  EmptyOutlined,
  EqualProportionOutlined,
  FilterOutlined,
  FolderAddOutlined,
  FolderMoveOutlined,
  FreezeColumnOutlined,
  FrozenLineOutlined,
  PasteOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SaveOutlined,
  ScissorOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  Spot1Outlined,
  Spot2Outlined,
  SummationOutlined,
  TableOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
} from '../'
export interface IconDescription {
  type: 'filled' | 'outlined'
  component: IconComponent
  name: string
  tagName: string
}
export interface IconGroupInfo {
  alert: IconDescription[]
  common: IconDescription[]
  direction: IconDescription[]
  edit: IconDescription[]
}
export const ComponentGroup: IconGroupInfo = {
  alert: [
    {
      type: 'filled',
      component: CheckCircleFilled,
      name: 'check-circle-filled',
      tagName: 'CheckCircleFilled',
    },
    {
      type: 'filled',
      component: CheckSquareFilled,
      name: 'check-square-filled',
      tagName: 'CheckSquareFilled',
    },
    {
      type: 'filled',
      component: CloseCircleFilled,
      name: 'close-circle-filled',
      tagName: 'CloseCircleFilled',
    },
    {
      type: 'filled',
      component: CloseSquareFilled,
      name: 'close-square-filled',
      tagName: 'CloseSquareFilled',
    },
    {
      type: 'filled',
      component: ExclamationCircleFilled,
      name: 'exclamation-circle-filled',
      tagName: 'ExclamationCircleFilled',
    },
    {
      type: 'filled',
      component: InfoCircleFilled,
      name: 'info-circle-filled',
      tagName: 'InfoCircleFilled',
    },
    {
      type: 'filled',
      component: QuestionCircleFilled,
      name: 'question-circle-filled',
      tagName: 'QuestionCircleFilled',
    },
    { type: 'filled', component: StopFilled, name: 'stop-filled', tagName: 'StopFilled' },
    { type: 'filled', component: WarningFilled, name: 'warning-filled', tagName: 'WarningFilled' },
    {
      type: 'outlined',
      component: CheckOutlined,
      name: 'check-outlined',
      tagName: 'CheckOutlined',
    },
    {
      type: 'outlined',
      component: CheckCircleOutlined,
      name: 'check-circle-outlined',
      tagName: 'CheckCircleOutlined',
    },
    {
      type: 'outlined',
      component: CheckSquareOutlined,
      name: 'check-square-outlined',
      tagName: 'CheckSquareOutlined',
    },
    {
      type: 'outlined',
      component: CloseOutlined,
      name: 'close-outlined',
      tagName: 'CloseOutlined',
    },
    {
      type: 'outlined',
      component: CloseCircleOutlined,
      name: 'close-circle-outlined',
      tagName: 'CloseCircleOutlined',
    },
    {
      type: 'outlined',
      component: CloseSquareOutlined,
      name: 'close-square-outlined',
      tagName: 'CloseSquareOutlined',
    },
    {
      type: 'outlined',
      component: ExclamationOutlined,
      name: 'exclamation-outlined',
      tagName: 'ExclamationOutlined',
    },
    {
      type: 'outlined',
      component: ExclamationCircleOutlined,
      name: 'exclamation-circle-outlined',
      tagName: 'ExclamationCircleOutlined',
    },
    { type: 'outlined', component: InfoOutlined, name: 'info-outlined', tagName: 'InfoOutlined' },
    {
      type: 'outlined',
      component: InfoCircleOutlined,
      name: 'info-circle-outlined',
      tagName: 'InfoCircleOutlined',
    },
    {
      type: 'outlined',
      component: MinusOutlined,
      name: 'minus-outlined',
      tagName: 'MinusOutlined',
    },
    {
      type: 'outlined',
      component: MinusSquareOutlined,
      name: 'minus-square-outlined',
      tagName: 'MinusSquareOutlined',
    },
    { type: 'outlined', component: PlusOutlined, name: 'plus-outlined', tagName: 'PlusOutlined' },
    {
      type: 'outlined',
      component: PlusSquareOutlined,
      name: 'plus-square-outlined',
      tagName: 'PlusSquareOutlined',
    },
    {
      type: 'outlined',
      component: QuestionOutlined,
      name: 'question-outlined',
      tagName: 'QuestionOutlined',
    },
    {
      type: 'outlined',
      component: QuestionCircleOutlined,
      name: 'question-circle-outlined',
      tagName: 'QuestionCircleOutlined',
    },
    { type: 'outlined', component: StopOutlined, name: 'stop-outlined', tagName: 'StopOutlined' },
    {
      type: 'outlined',
      component: WarningOutlined,
      name: 'warning-outlined',
      tagName: 'WarningOutlined',
    },
  ],
  common: [
    { type: 'filled', component: AlarmFilled, name: 'alarm-filled', tagName: 'AlarmFilled' },
    {
      type: 'filled',
      component: AlarmClockFilled,
      name: 'alarm-clock-filled',
      tagName: 'AlarmClockFilled',
    },
    {
      type: 'filled',
      component: AppStoreFilled,
      name: 'app-store-filled',
      tagName: 'AppStoreFilled',
    },
    { type: 'filled', component: ApproveFilled, name: 'approve-filled', tagName: 'ApproveFilled' },
    { type: 'filled', component: ArchiveFilled, name: 'archive-filled', tagName: 'ArchiveFilled' },
    {
      type: 'filled',
      component: AssetMonitorFilled,
      name: 'asset-monitor-filled',
      tagName: 'AssetMonitorFilled',
    },
    { type: 'filled', component: AudioFilled, name: 'audio-filled', tagName: 'AudioFilled' },
    {
      type: 'filled',
      component: BankCardFilled,
      name: 'bank-card-filled',
      tagName: 'BankCardFilled',
    },
    { type: 'filled', component: BellFilled, name: 'bell-filled', tagName: 'BellFilled' },
    { type: 'filled', component: BlockFilled, name: 'block-filled', tagName: 'BlockFilled' },
    {
      type: 'filled',
      component: BookmarkFilled,
      name: 'bookmark-filled',
      tagName: 'BookmarkFilled',
    },
    {
      type: 'filled',
      component: BuildingFilled,
      name: 'building-filled',
      tagName: 'BuildingFilled',
    },
    { type: 'filled', component: BulbFilled, name: 'bulb-filled', tagName: 'BulbFilled' },
    {
      type: 'filled',
      component: CalculatorFilled,
      name: 'calculator-filled',
      tagName: 'CalculatorFilled',
    },
    {
      type: 'filled',
      component: CalendarFilled,
      name: 'calendar-filled',
      tagName: 'CalendarFilled',
    },
    { type: 'filled', component: CameraFilled, name: 'camera-filled', tagName: 'CameraFilled' },
    { type: 'filled', component: ChatFilled, name: 'chat-filled', tagName: 'ChatFilled' },
    { type: 'filled', component: CloudFilled, name: 'cloud-filled', tagName: 'CloudFilled' },
    {
      type: 'filled',
      component: CloudDownloadFilled,
      name: 'cloud-download-filled',
      tagName: 'CloudDownloadFilled',
    },
    {
      type: 'filled',
      component: CloudUploadFilled,
      name: 'cloud-upload-filled',
      tagName: 'CloudUploadFilled',
    },
    {
      type: 'filled',
      component: CollectionFilled,
      name: 'collection-filled',
      tagName: 'CollectionFilled',
    },
    {
      type: 'filled',
      component: DataMonitorFilled,
      name: 'data-monitor-filled',
      tagName: 'DataMonitorFilled',
    },
    { type: 'filled', component: DislikeFilled, name: 'dislike-filled', tagName: 'DislikeFilled' },
    {
      type: 'filled',
      component: DocumentFilled,
      name: 'document-filled',
      tagName: 'DocumentFilled',
    },
    {
      type: 'filled',
      component: DocumentExclamationFilled,
      name: 'document-exclamation-filled',
      tagName: 'DocumentExclamationFilled',
    },
    { type: 'filled', component: EndDateFilled, name: 'end-date-filled', tagName: 'EndDateFilled' },
    {
      type: 'filled',
      component: ExpressionFilled,
      name: 'expression-filled',
      tagName: 'ExpressionFilled',
    },
    { type: 'filled', component: FileFilled, name: 'file-filled', tagName: 'FileFilled' },
    { type: 'filled', component: FireFilled, name: 'fire-filled', tagName: 'FireFilled' },
    { type: 'filled', component: FlagFilled, name: 'flag-filled', tagName: 'FlagFilled' },
    { type: 'filled', component: FolderFilled, name: 'folder-filled', tagName: 'FolderFilled' },
    {
      type: 'filled',
      component: FolderOpenFilled,
      name: 'folder-open-filled',
      tagName: 'FolderOpenFilled',
    },
    { type: 'filled', component: HeartFilled, name: 'heart-filled', tagName: 'HeartFilled' },
    { type: 'filled', component: HomeFilled, name: 'home-filled', tagName: 'HomeFilled' },
    { type: 'filled', component: KeyFilled, name: 'key-filled', tagName: 'KeyFilled' },
    {
      type: 'filled',
      component: LightningFilled,
      name: 'lightning-filled',
      tagName: 'LightningFilled',
    },
    { type: 'filled', component: LikeFilled, name: 'like-filled', tagName: 'LikeFilled' },
    {
      type: 'filled',
      component: LocationFilled,
      name: 'location-filled',
      tagName: 'LocationFilled',
    },
    { type: 'filled', component: LockFilled, name: 'lock-filled', tagName: 'LockFilled' },
    { type: 'filled', component: MailFilled, name: 'mail-filled', tagName: 'MailFilled' },
    {
      type: 'filled',
      component: MailOpenFilled,
      name: 'mail-open-filled',
      tagName: 'MailOpenFilled',
    },
    {
      type: 'filled',
      component: MailSendFilled,
      name: 'mail-send-filled',
      tagName: 'MailSendFilled',
    },
    { type: 'filled', component: ManFilled, name: 'man-filled', tagName: 'ManFilled' },
    { type: 'filled', component: MessageFilled, name: 'message-filled', tagName: 'MessageFilled' },
    { type: 'filled', component: MobileFilled, name: 'mobile-filled', tagName: 'MobileFilled' },
    { type: 'filled', component: MonitorFilled, name: 'monitor-filled', tagName: 'MonitorFilled' },
    { type: 'filled', component: MoonFilled, name: 'moon-filled', tagName: 'MoonFilled' },
    { type: 'filled', component: PadFilled, name: 'pad-filled', tagName: 'PadFilled' },
    { type: 'filled', component: PauseFilled, name: 'pause-filled', tagName: 'PauseFilled' },
    { type: 'filled', component: PhoneFilled, name: 'phone-filled', tagName: 'PhoneFilled' },
    { type: 'filled', component: PictureFilled, name: 'picture-filled', tagName: 'PictureFilled' },
    { type: 'filled', component: PinFilled, name: 'pin-filled', tagName: 'PinFilled' },
    { type: 'filled', component: PlayFilled, name: 'play-filled', tagName: 'PlayFilled' },
    { type: 'filled', component: PrinterFilled, name: 'printer-filled', tagName: 'PrinterFilled' },
    { type: 'filled', component: QrCodeFilled, name: 'qr-code-filled', tagName: 'QrCodeFilled' },
    {
      type: 'filled',
      component: RelationFilled,
      name: 'relation-filled',
      tagName: 'RelationFilled',
    },
    { type: 'filled', component: RmbFilled, name: 'rmb-filled', tagName: 'RmbFilled' },
    { type: 'filled', component: SadFilled, name: 'sad-filled', tagName: 'SadFilled' },
    { type: 'filled', component: SettingFilled, name: 'setting-filled', tagName: 'SettingFilled' },
    {
      type: 'filled',
      component: ShoppingFilled,
      name: 'shopping-filled',
      tagName: 'ShoppingFilled',
    },
    { type: 'filled', component: SkinFilled, name: 'skin-filled', tagName: 'SkinFilled' },
    { type: 'filled', component: SoundFilled, name: 'sound-filled', tagName: 'SoundFilled' },
    { type: 'filled', component: StarFilled, name: 'star-filled', tagName: 'StarFilled' },
    {
      type: 'filled',
      component: StartDateFilled,
      name: 'start-date-filled',
      tagName: 'StartDateFilled',
    },
    { type: 'filled', component: SunFilled, name: 'sun-filled', tagName: 'SunFilled' },
    { type: 'filled', component: TagFilled, name: 'tag-filled', tagName: 'TagFilled' },
    { type: 'filled', component: TaskFilled, name: 'task-filled', tagName: 'TaskFilled' },
    {
      type: 'filled',
      component: TemplateFilled,
      name: 'template-filled',
      tagName: 'TemplateFilled',
    },
    { type: 'filled', component: TimeFilled, name: 'time-filled', tagName: 'TimeFilled' },
    { type: 'filled', component: ToolFilled, name: 'tool-filled', tagName: 'ToolFilled' },
    { type: 'filled', component: TravelFilled, name: 'travel-filled', tagName: 'TravelFilled' },
    { type: 'filled', component: TruckFilled, name: 'truck-filled', tagName: 'TruckFilled' },
    {
      type: 'filled',
      component: UmbrellaFilled,
      name: 'umbrella-filled',
      tagName: 'UmbrellaFilled',
    },
    { type: 'filled', component: UnlockFilled, name: 'unlock-filled', tagName: 'UnlockFilled' },
    { type: 'filled', component: UpdateFilled, name: 'update-filled', tagName: 'UpdateFilled' },
    { type: 'filled', component: UserFilled, name: 'user-filled', tagName: 'UserFilled' },
    {
      type: 'filled',
      component: VideoCameraFilled,
      name: 'video-camera-filled',
      tagName: 'VideoCameraFilled',
    },
    { type: 'filled', component: WebpageFilled, name: 'webpage-filled', tagName: 'WebpageFilled' },
    {
      type: 'outlined',
      component: AlarmOutlined,
      name: 'alarm-outlined',
      tagName: 'AlarmOutlined',
    },
    {
      type: 'outlined',
      component: AlarmClockOutlined,
      name: 'alarm-clock-outlined',
      tagName: 'AlarmClockOutlined',
    },
    {
      type: 'outlined',
      component: AppStoreOutlined,
      name: 'app-store-outlined',
      tagName: 'AppStoreOutlined',
    },
    {
      type: 'outlined',
      component: ApproveOutlined,
      name: 'approve-outlined',
      tagName: 'ApproveOutlined',
    },
    {
      type: 'outlined',
      component: ArchiveOutlined,
      name: 'archive-outlined',
      tagName: 'ArchiveOutlined',
    },
    {
      type: 'outlined',
      component: AssetMonitorOutlined,
      name: 'asset-monitor-outlined',
      tagName: 'AssetMonitorOutlined',
    },
    {
      type: 'outlined',
      component: AudioOutlined,
      name: 'audio-outlined',
      tagName: 'AudioOutlined',
    },
    {
      type: 'outlined',
      component: BankCardOutlined,
      name: 'bank-card-outlined',
      tagName: 'BankCardOutlined',
    },
    { type: 'outlined', component: BarsOutlined, name: 'bars-outlined', tagName: 'BarsOutlined' },
    { type: 'outlined', component: BellOutlined, name: 'bell-outlined', tagName: 'BellOutlined' },
    {
      type: 'outlined',
      component: BlockOutlined,
      name: 'block-outlined',
      tagName: 'BlockOutlined',
    },
    {
      type: 'outlined',
      component: BookmarkOutlined,
      name: 'bookmark-outlined',
      tagName: 'BookmarkOutlined',
    },
    {
      type: 'outlined',
      component: BuildingOutlined,
      name: 'building-outlined',
      tagName: 'BuildingOutlined',
    },
    { type: 'outlined', component: BulbOutlined, name: 'bulb-outlined', tagName: 'BulbOutlined' },
    {
      type: 'outlined',
      component: BusinessCardTransverseOutlined,
      name: 'business-card-transverse-outlined',
      tagName: 'BusinessCardTransverseOutlined',
    },
    {
      type: 'outlined',
      component: BusinessCardOutlined,
      name: 'business-card-outlined',
      tagName: 'BusinessCardOutlined',
    },
    {
      type: 'outlined',
      component: CalculatorOutlined,
      name: 'calculator-outlined',
      tagName: 'CalculatorOutlined',
    },
    {
      type: 'outlined',
      component: CalendarOutlined,
      name: 'calendar-outlined',
      tagName: 'CalendarOutlined',
    },
    {
      type: 'outlined',
      component: CameraOutlined,
      name: 'camera-outlined',
      tagName: 'CameraOutlined',
    },
    { type: 'outlined', component: ChatOutlined, name: 'chat-outlined', tagName: 'ChatOutlined' },
    {
      type: 'outlined',
      component: CloseCodeOutlined,
      name: 'close-code-outlined',
      tagName: 'CloseCodeOutlined',
    },
    {
      type: 'outlined',
      component: CloudOutlined,
      name: 'cloud-outlined',
      tagName: 'CloudOutlined',
    },
    {
      type: 'outlined',
      component: CloudDownloadOutlined,
      name: 'cloud-download-outlined',
      tagName: 'CloudDownloadOutlined',
    },
    {
      type: 'outlined',
      component: CloudUploadOutlined,
      name: 'cloud-upload-outlined',
      tagName: 'CloudUploadOutlined',
    },
    {
      type: 'outlined',
      component: CollectionOutlined,
      name: 'collection-outlined',
      tagName: 'CollectionOutlined',
    },
    {
      type: 'outlined',
      component: DataMonitorOutlined,
      name: 'data-monitor-outlined',
      tagName: 'DataMonitorOutlined',
    },
    {
      type: 'outlined',
      component: DiagramOutlined,
      name: 'diagram-outlined',
      tagName: 'DiagramOutlined',
    },
    {
      type: 'outlined',
      component: DislikeOutlined,
      name: 'dislike-outlined',
      tagName: 'DislikeOutlined',
    },
    {
      type: 'outlined',
      component: DocumentOutlined,
      name: 'document-outlined',
      tagName: 'DocumentOutlined',
    },
    {
      type: 'outlined',
      component: DocumentExclamationOutlined,
      name: 'document-exclamation-outlined',
      tagName: 'DocumentExclamationOutlined',
    },
    {
      type: 'outlined',
      component: DownloadOutlined,
      name: 'download-outlined',
      tagName: 'DownloadOutlined',
    },
    {
      type: 'outlined',
      component: EndDateOutlined,
      name: 'end-date-outlined',
      tagName: 'EndDateOutlined',
    },
    {
      type: 'outlined',
      component: ExportOutlined,
      name: 'export-outlined',
      tagName: 'ExportOutlined',
    },
    {
      type: 'outlined',
      component: ExpressionOutlined,
      name: 'expression-outlined',
      tagName: 'ExpressionOutlined',
    },
    { type: 'outlined', component: EyeOutlined, name: 'eye-outlined', tagName: 'EyeOutlined' },
    {
      type: 'outlined',
      component: EyeInvisibleOutlined,
      name: 'eye-invisible-outlined',
      tagName: 'EyeInvisibleOutlined',
    },
    { type: 'outlined', component: FileOutlined, name: 'file-outlined', tagName: 'FileOutlined' },
    {
      type: 'outlined',
      component: FileExcelOutlined,
      name: 'file-excel-outlined',
      tagName: 'FileExcelOutlined',
    },
    {
      type: 'outlined',
      component: FileExeOutlined,
      name: 'file-exe-outlined',
      tagName: 'FileExeOutlined',
    },
    {
      type: 'outlined',
      component: FileJpgOutlined,
      name: 'file-jpg-outlined',
      tagName: 'FileJpgOutlined',
    },
    {
      type: 'outlined',
      component: FileKeynoteOutlined,
      name: 'file-keynote-outlined',
      tagName: 'FileKeynoteOutlined',
    },
    {
      type: 'outlined',
      component: FileMusicOutlined,
      name: 'file-music-outlined',
      tagName: 'FileMusicOutlined',
    },
    {
      type: 'outlined',
      component: FilePdfOutlined,
      name: 'file-pdf-outlined',
      tagName: 'FilePdfOutlined',
    },
    {
      type: 'outlined',
      component: FilePptOutlined,
      name: 'file-ppt-outlined',
      tagName: 'FilePptOutlined',
    },
    {
      type: 'outlined',
      component: FileQuestionOutlined,
      name: 'file-question-outlined',
      tagName: 'FileQuestionOutlined',
    },
    {
      type: 'outlined',
      component: FileTxtOutlined,
      name: 'file-txt-outlined',
      tagName: 'FileTxtOutlined',
    },
    {
      type: 'outlined',
      component: FileVideoOutlined,
      name: 'file-video-outlined',
      tagName: 'FileVideoOutlined',
    },
    {
      type: 'outlined',
      component: FileWordOutlined,
      name: 'file-word-outlined',
      tagName: 'FileWordOutlined',
    },
    {
      type: 'outlined',
      component: FileZipOutlined,
      name: 'file-zip-outlined',
      tagName: 'FileZipOutlined',
    },
    { type: 'outlined', component: FireOutlined, name: 'fire-outlined', tagName: 'FireOutlined' },
    { type: 'outlined', component: FlagOutlined, name: 'flag-outlined', tagName: 'FlagOutlined' },
    {
      type: 'outlined',
      component: FolderOutlined,
      name: 'folder-outlined',
      tagName: 'FolderOutlined',
    },
    {
      type: 'outlined',
      component: FolderOpenOutlined,
      name: 'folder-open-outlined',
      tagName: 'FolderOpenOutlined',
    },
    {
      type: 'outlined',
      component: GlobalOutlined,
      name: 'global-outlined',
      tagName: 'GlobalOutlined',
    },
    {
      type: 'outlined',
      component: HeartOutlined,
      name: 'heart-outlined',
      tagName: 'HeartOutlined',
    },
    { type: 'outlined', component: HomeOutlined, name: 'home-outlined', tagName: 'HomeOutlined' },
    {
      type: 'outlined',
      component: ImportOutlined,
      name: 'import-outlined',
      tagName: 'ImportOutlined',
    },
    { type: 'outlined', component: KeyOutlined, name: 'key-outlined', tagName: 'KeyOutlined' },
    {
      type: 'outlined',
      component: LightningOutlined,
      name: 'lightning-outlined',
      tagName: 'LightningOutlined',
    },
    { type: 'outlined', component: LikeOutlined, name: 'like-outlined', tagName: 'LikeOutlined' },
    { type: 'outlined', component: LinkOutlined, name: 'link-outlined', tagName: 'LinkOutlined' },
    {
      type: 'outlined',
      component: LocationOutlined,
      name: 'location-outlined',
      tagName: 'LocationOutlined',
    },
    { type: 'outlined', component: LockOutlined, name: 'lock-outlined', tagName: 'LockOutlined' },
    { type: 'outlined', component: MailOutlined, name: 'mail-outlined', tagName: 'MailOutlined' },
    {
      type: 'outlined',
      component: MailOpenOutlined,
      name: 'mail-open-outlined',
      tagName: 'MailOpenOutlined',
    },
    {
      type: 'outlined',
      component: MailSendOutlined,
      name: 'mail-send-outlined',
      tagName: 'MailSendOutlined',
    },
    { type: 'outlined', component: ManOutlined, name: 'man-outlined', tagName: 'ManOutlined' },
    { type: 'outlined', component: MenuOutlined, name: 'menu-outlined', tagName: 'MenuOutlined' },
    {
      type: 'outlined',
      component: MessageOutlined,
      name: 'message-outlined',
      tagName: 'MessageOutlined',
    },
    {
      type: 'outlined',
      component: MobileOutlined,
      name: 'mobile-outlined',
      tagName: 'MobileOutlined',
    },
    {
      type: 'outlined',
      component: MonitorOutlined,
      name: 'monitor-outlined',
      tagName: 'MonitorOutlined',
    },
    { type: 'outlined', component: MoonOutlined, name: 'moon-outlined', tagName: 'MoonOutlined' },
    { type: 'outlined', component: PadOutlined, name: 'pad-outlined', tagName: 'PadOutlined' },
    {
      type: 'outlined',
      component: PauseOutlined,
      name: 'pause-outlined',
      tagName: 'PauseOutlined',
    },
    {
      type: 'outlined',
      component: PhoneOutlined,
      name: 'phone-outlined',
      tagName: 'PhoneOutlined',
    },
    {
      type: 'outlined',
      component: PictureOutlined,
      name: 'picture-outlined',
      tagName: 'PictureOutlined',
    },
    { type: 'outlined', component: PinOutlined, name: 'pin-outlined', tagName: 'PinOutlined' },
    { type: 'outlined', component: PlayOutlined, name: 'play-outlined', tagName: 'PlayOutlined' },
    {
      type: 'outlined',
      component: PowerOffOutlined,
      name: 'power-off-outlined',
      tagName: 'PowerOffOutlined',
    },
    {
      type: 'outlined',
      component: PrinterOutlined,
      name: 'printer-outlined',
      tagName: 'PrinterOutlined',
    },
    {
      type: 'outlined',
      component: QrCodeOutlined,
      name: 'qr-code-outlined',
      tagName: 'QrCodeOutlined',
    },
    {
      type: 'outlined',
      component: RelationOutlined,
      name: 'relation-outlined',
      tagName: 'RelationOutlined',
    },
    {
      type: 'outlined',
      component: ResetOutlined,
      name: 'reset-outlined',
      tagName: 'ResetOutlined',
    },
    { type: 'outlined', component: RmbOutlined, name: 'rmb-outlined', tagName: 'RmbOutlined' },
    { type: 'outlined', component: SadOutlined, name: 'sad-outlined', tagName: 'SadOutlined' },
    { type: 'outlined', component: ScanOutlined, name: 'scan-outlined', tagName: 'ScanOutlined' },
    {
      type: 'outlined',
      component: SearchOutlined,
      name: 'search-outlined',
      tagName: 'SearchOutlined',
    },
    {
      type: 'outlined',
      component: SendOutOutlined,
      name: 'send-out-outlined',
      tagName: 'SendOutOutlined',
    },
    {
      type: 'outlined',
      component: SettingOutlined,
      name: 'setting-outlined',
      tagName: 'SettingOutlined',
    },
    {
      type: 'outlined',
      component: ShareOutlined,
      name: 'share-outlined',
      tagName: 'ShareOutlined',
    },
    { type: 'outlined', component: ShopOutlined, name: 'shop-outlined', tagName: 'ShopOutlined' },
    {
      type: 'outlined',
      component: ShoppingOutlined,
      name: 'shopping-outlined',
      tagName: 'ShoppingOutlined',
    },
    {
      type: 'outlined',
      component: ShowCodeOutlined,
      name: 'show-code-outlined',
      tagName: 'ShowCodeOutlined',
    },
    { type: 'outlined', component: SkinOutlined, name: 'skin-outlined', tagName: 'SkinOutlined' },
    {
      type: 'outlined',
      component: SoundOutlined,
      name: 'sound-outlined',
      tagName: 'SoundOutlined',
    },
    { type: 'outlined', component: StarOutlined, name: 'star-outlined', tagName: 'StarOutlined' },
    {
      type: 'outlined',
      component: StartDateOutlined,
      name: 'start-date-outlined',
      tagName: 'StartDateOutlined',
    },
    { type: 'outlined', component: SunOutlined, name: 'sun-outlined', tagName: 'SunOutlined' },
    {
      type: 'outlined',
      component: SynchronizeOutlined,
      name: 'synchronize-outlined',
      tagName: 'SynchronizeOutlined',
    },
    { type: 'outlined', component: TagOutlined, name: 'tag-outlined', tagName: 'TagOutlined' },
    { type: 'outlined', component: TaskOutlined, name: 'task-outlined', tagName: 'TaskOutlined' },
    {
      type: 'outlined',
      component: TemplateOutlined,
      name: 'template-outlined',
      tagName: 'TemplateOutlined',
    },
    { type: 'outlined', component: TimeOutlined, name: 'time-outlined', tagName: 'TimeOutlined' },
    {
      type: 'outlined',
      component: TimeRewindOutlined,
      name: 'time-rewind-outlined',
      tagName: 'TimeRewindOutlined',
    },
    { type: 'outlined', component: ToolOutlined, name: 'tool-outlined', tagName: 'ToolOutlined' },
    {
      type: 'outlined',
      component: TravelOutlined,
      name: 'travel-outlined',
      tagName: 'TravelOutlined',
    },
    {
      type: 'outlined',
      component: TruckOutlined,
      name: 'truck-outlined',
      tagName: 'TruckOutlined',
    },
    {
      type: 'outlined',
      component: UmberOutlined,
      name: 'umber-outlined',
      tagName: 'UmberOutlined',
    },
    {
      type: 'outlined',
      component: UmbrellaOutlined,
      name: 'umbrella-outlined',
      tagName: 'UmbrellaOutlined',
    },
    {
      type: 'outlined',
      component: UnlockOutlined,
      name: 'unlock-outlined',
      tagName: 'UnlockOutlined',
    },
    {
      type: 'outlined',
      component: UpdateOutlined,
      name: 'update-outlined',
      tagName: 'UpdateOutlined',
    },
    {
      type: 'outlined',
      component: UploadOutlined,
      name: 'upload-outlined',
      tagName: 'UploadOutlined',
    },
    { type: 'outlined', component: UserOutlined, name: 'user-outlined', tagName: 'UserOutlined' },
    {
      type: 'outlined',
      component: UserAddOutlined,
      name: 'user-add-outlined',
      tagName: 'UserAddOutlined',
    },
    {
      type: 'outlined',
      component: UsersOutlined,
      name: 'users-outlined',
      tagName: 'UsersOutlined',
    },
    {
      type: 'outlined',
      component: VideoCameraOutlined,
      name: 'video-camera-outlined',
      tagName: 'VideoCameraOutlined',
    },
    {
      type: 'outlined',
      component: WebpageOutlined,
      name: 'webpage-outlined',
      tagName: 'WebpageOutlined',
    },
    {
      type: 'outlined',
      component: WomanOutlined,
      name: 'woman-outlined',
      tagName: 'WomanOutlined',
    },
  ],
  direction: [
    {
      type: 'filled',
      component: CaretDownFilled,
      name: 'caret-down-filled',
      tagName: 'CaretDownFilled',
    },
    {
      type: 'filled',
      component: CaretLeftFilled,
      name: 'caret-left-filled',
      tagName: 'CaretLeftFilled',
    },
    {
      type: 'filled',
      component: CaretRightFilled,
      name: 'caret-right-filled',
      tagName: 'CaretRightFilled',
    },
    { type: 'filled', component: CaretUpFilled, name: 'caret-up-filled', tagName: 'CaretUpFilled' },
    {
      type: 'outlined',
      component: ArrowDownOutlined,
      name: 'arrow-down-outlined',
      tagName: 'ArrowDownOutlined',
    },
    {
      type: 'outlined',
      component: ArrowLeftOutlined,
      name: 'arrow-left-outlined',
      tagName: 'ArrowLeftOutlined',
    },
    {
      type: 'outlined',
      component: ArrowRightOutlined,
      name: 'arrow-right-outlined',
      tagName: 'ArrowRightOutlined',
    },
    {
      type: 'outlined',
      component: ArrowUpOutlined,
      name: 'arrow-up-outlined',
      tagName: 'ArrowUpOutlined',
    },
    {
      type: 'outlined',
      component: DirectionDownOutlined,
      name: 'direction-down-outlined',
      tagName: 'DirectionDownOutlined',
    },
    {
      type: 'outlined',
      component: DirectionLeftOutlined,
      name: 'direction-left-outlined',
      tagName: 'DirectionLeftOutlined',
    },
    {
      type: 'outlined',
      component: DirectionRightOutlined,
      name: 'direction-right-outlined',
      tagName: 'DirectionRightOutlined',
    },
    {
      type: 'outlined',
      component: DirectionUpOutlined,
      name: 'direction-up-outlined',
      tagName: 'DirectionUpOutlined',
    },
    { type: 'outlined', component: DownOutlined, name: 'down-outlined', tagName: 'DownOutlined' },
    {
      type: 'outlined',
      component: ExpandOutlined,
      name: 'expand-outlined',
      tagName: 'ExpandOutlined',
    },
    {
      type: 'outlined',
      component: FullscreenOutlined,
      name: 'fullscreen-outlined',
      tagName: 'FullscreenOutlined',
    },
    {
      type: 'outlined',
      component: FullscreenExitOutlined,
      name: 'fullscreen-exit-outlined',
      tagName: 'FullscreenExitOutlined',
    },
    { type: 'outlined', component: LeftOutlined, name: 'left-outlined', tagName: 'LeftOutlined' },
    {
      type: 'outlined',
      component: LeftRightOutlined,
      name: 'left-right-outlined',
      tagName: 'LeftRightOutlined',
    },
    {
      type: 'outlined',
      component: MenuFoldOutlined,
      name: 'menu-fold-outlined',
      tagName: 'MenuFoldOutlined',
    },
    {
      type: 'outlined',
      component: MenuUnfoldOutlined,
      name: 'menu-unfold-outlined',
      tagName: 'MenuUnfoldOutlined',
    },
    {
      type: 'outlined',
      component: RightOutlined,
      name: 'right-outlined',
      tagName: 'RightOutlined',
    },
    {
      type: 'outlined',
      component: ShrinkOutlined,
      name: 'shrink-outlined',
      tagName: 'ShrinkOutlined',
    },
    {
      type: 'outlined',
      component: ToBottomOutlined,
      name: 'to-bottom-outlined',
      tagName: 'ToBottomOutlined',
    },
    {
      type: 'outlined',
      component: ToTopOutlined,
      name: 'to-top-outlined',
      tagName: 'ToTopOutlined',
    },
    { type: 'outlined', component: UpOutlined, name: 'up-outlined', tagName: 'UpOutlined' },
  ],
  edit: [
    { type: 'filled', component: CopyFilled, name: 'copy-filled', tagName: 'CopyFilled' },
    { type: 'filled', component: DeleteFilled, name: 'delete-filled', tagName: 'DeleteFilled' },
    { type: 'filled', component: DetailsFilled, name: 'details-filled', tagName: 'DetailsFilled' },
    {
      type: 'filled',
      component: DuplicateFilled,
      name: 'duplicate-filled',
      tagName: 'DuplicateFilled',
    },
    { type: 'filled', component: EditFilled, name: 'edit-filled', tagName: 'EditFilled' },
    {
      type: 'filled',
      component: EllipsisCircleFilled,
      name: 'ellipsis-circle-filled',
      tagName: 'EllipsisCircleFilled',
    },
    { type: 'filled', component: EmptyFilled, name: 'empty-filled', tagName: 'EmptyFilled' },
    { type: 'filled', component: FilterFilled, name: 'filter-filled', tagName: 'FilterFilled' },
    {
      type: 'filled',
      component: FolderAddFilled,
      name: 'folder-add-filled',
      tagName: 'FolderAddFilled',
    },
    {
      type: 'filled',
      component: FolderMoveFilled,
      name: 'folder-move-filled',
      tagName: 'FolderMoveFilled',
    },
    { type: 'filled', component: PasteFilled, name: 'paste-filled', tagName: 'PasteFilled' },
    {
      type: 'outlined',
      component: AverageOutlined,
      name: 'average-outlined',
      tagName: 'AverageOutlined',
    },
    {
      type: 'outlined',
      component: ColumnHeightOutlined,
      name: 'column-height-outlined',
      tagName: 'ColumnHeightOutlined',
    },
    {
      type: 'outlined',
      component: ColumnsOutlined,
      name: 'columns-outlined',
      tagName: 'ColumnsOutlined',
    },
    { type: 'outlined', component: CopyOutlined, name: 'copy-outlined', tagName: 'CopyOutlined' },
    {
      type: 'outlined',
      component: DeleteOutlined,
      name: 'delete-outlined',
      tagName: 'DeleteOutlined',
    },
    {
      type: 'outlined',
      component: DetailsOutlined,
      name: 'details-outlined',
      tagName: 'DetailsOutlined',
    },
    {
      type: 'outlined',
      component: DocumentSearchOutlined,
      name: 'document-search-outlined',
      tagName: 'DocumentSearchOutlined',
    },
    { type: 'outlined', component: DragOutlined, name: 'drag-outlined', tagName: 'DragOutlined' },
    {
      type: 'outlined',
      component: DuplicateOutlined,
      name: 'duplicate-outlined',
      tagName: 'DuplicateOutlined',
    },
    { type: 'outlined', component: EditOutlined, name: 'edit-outlined', tagName: 'EditOutlined' },
    {
      type: 'outlined',
      component: EllipsisCircleOutlined,
      name: 'ellipsis-circle-outlined',
      tagName: 'EllipsisCircleOutlined',
    },
    {
      type: 'outlined',
      component: EmptyOutlined,
      name: 'empty-outlined',
      tagName: 'EmptyOutlined',
    },
    {
      type: 'outlined',
      component: EqualProportionOutlined,
      name: 'equal-proportion-outlined',
      tagName: 'EqualProportionOutlined',
    },
    {
      type: 'outlined',
      component: FilterOutlined,
      name: 'filter-outlined',
      tagName: 'FilterOutlined',
    },
    {
      type: 'outlined',
      component: FolderAddOutlined,
      name: 'folder-add-outlined',
      tagName: 'FolderAddOutlined',
    },
    {
      type: 'outlined',
      component: FolderMoveOutlined,
      name: 'folder-move-outlined',
      tagName: 'FolderMoveOutlined',
    },
    {
      type: 'outlined',
      component: FreezeColumnOutlined,
      name: 'freeze-column-outlined',
      tagName: 'FreezeColumnOutlined',
    },
    {
      type: 'outlined',
      component: FrozenLineOutlined,
      name: 'frozen-line-outlined',
      tagName: 'FrozenLineOutlined',
    },
    {
      type: 'outlined',
      component: PasteOutlined,
      name: 'paste-outlined',
      tagName: 'PasteOutlined',
    },
    {
      type: 'outlined',
      component: RotateLeftOutlined,
      name: 'rotate-left-outlined',
      tagName: 'RotateLeftOutlined',
    },
    {
      type: 'outlined',
      component: RotateRightOutlined,
      name: 'rotate-right-outlined',
      tagName: 'RotateRightOutlined',
    },
    { type: 'outlined', component: SaveOutlined, name: 'save-outlined', tagName: 'SaveOutlined' },
    {
      type: 'outlined',
      component: ScissorOutlined,
      name: 'scissor-outlined',
      tagName: 'ScissorOutlined',
    },
    {
      type: 'outlined',
      component: SortAscendingOutlined,
      name: 'sort-ascending-outlined',
      tagName: 'SortAscendingOutlined',
    },
    {
      type: 'outlined',
      component: SortDescendingOutlined,
      name: 'sort-descending-outlined',
      tagName: 'SortDescendingOutlined',
    },
    {
      type: 'outlined',
      component: Spot1Outlined,
      name: 'spot-1-outlined',
      tagName: 'Spot1Outlined',
    },
    {
      type: 'outlined',
      component: Spot2Outlined,
      name: 'spot-2-outlined',
      tagName: 'Spot2Outlined',
    },
    {
      type: 'outlined',
      component: SummationOutlined,
      name: 'summation-outlined',
      tagName: 'SummationOutlined',
    },
    {
      type: 'outlined',
      component: TableOutlined,
      name: 'table-outlined',
      tagName: 'TableOutlined',
    },
    {
      type: 'outlined',
      component: ZoomInOutlined,
      name: 'zoom-in-outlined',
      tagName: 'ZoomInOutlined',
    },
    {
      type: 'outlined',
      component: ZoomOutOutlined,
      name: 'zoom-out-outlined',
      tagName: 'ZoomOutOutlined',
    },
  ],
}
